- name: Configure Erlaubnis Address List
  hosts: Mikrotiks
  gather_facts: false
  tasks:
    - name: Set Addresses to List
      community.routeros.command:
        commands:
          - /ip firewall address-list set list=Erlaubnis address=192.168.2.120/32 numbers=0 comment=crynow_sa_pc
          - :local from 1;:local i 0;:foreach id in=[/ip firewall address-list find] do={:if ($i >= $from) do={/ip firewall address-list remove $id}; :set i ($i+1)}
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.74/32 comment=MacBook
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.132/32 comment=IT-1
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.94/32 comment=IT-2
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.87/32 comment=IT-3
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.61/32 comment=IT-4
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.125/32 comment=IT-5
          - /ip firewall address-list add list=Erlaubnis address=192.168.2.29/32 comment=W10-KVADM
          - /ip firewall address-list add list=Erlaubnis address=4.4.4.4/32 comment=Office
          - /ip firewall address-list add list=Erlaubnis address=1.1.1.1/32 comment=DataCenter
          - /ip firewall address-list add list=Erlaubnis address=10.1.1.20/32 comment=Zabbix
      tags:
        - setup
    - name: Remove unwanted List and Addresses
      community.routeros.command:
        commands:
          - /ip firewall address-list remove numbers=[find list!=Erlaubnis]
          - :local from 9;:local i 0;:foreach id in=[/ip firewall address-list find] do={:if ($i >= $from) do={/ip firewall address-list remove $id}; :set i ($i+1)}
      tags:
        - remove_list
    - name: Get Address List
      community.routeros.command:
        commands:
          - /ip firewall address-list print
      register: result
      tags:
        - print_result
    - name: Print Address List
      ansible.builtin.debug:
        var: result.stdout_lines
      tags:
        - print_result
